#!/usr/bin/env bun
//MISE description="List Buttondown newsletters with sanitized fields"

import { runResource } from '../../../../scripts/buttondown/api.mjs';

const output = await runResource('newsletters', {});
console.log(JSON.stringify(output, null, 2));
